name: Build ISO

on:
  push:
    tags:
      - 'v*.*.*'

permissions:
    contents: write

jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Update the system
        run: pacman -Syu --noconfirm
      - name: install necessary utils
        run: pacman -S archiso git bash github-cli --noconfirm
      - name: prepare build environment
        run: mkdir work out
      - name: build the image
				run: mkarchiso -v -w work/ -o out/ iso/ 
			- name: compress the image	
				run: xz out/*.iso
			- name: create a checksum file
				run: sha256sum out/* > out/checksums.txt
      - name: create a release
        uses: softprops/action-gh-release@v2
        with:
          files: out/*
          token: ${{ secrets.GITHUB_TOKEN }}

