name: Build ISO

on:
  push:
    branches: [main]


jobs:
  build-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
    steps:
      - name: Update the system
        run: pacman -Syu
      - name: install archiso
        run: pacman -S archiso
      - name: prepare build environment
        run: mkdir work out
      - name: build the image
        run: mkarchiso -v -w work/ -o out/ iso/


