name: Test ISO Compilation

on: [push, pull_request]


jobs:
  compile-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Update the system
        run: pacman -Syu --noconfirm
      - name: install necessary utils
        run: pacman -S archiso git bash github-cli --noconfirm
      - name: add blackarch keys
        run: |
          curl -O https://blackarch.org/strap.sh
          bash strap.sh
          pacman -Syu
      - name: prepare build environment
        run: mkdir work out
      - name: build the image
        run: mkarchiso -v -w work/ -o out/ iso/ 
