name: Test ISO Compilation

on: [push, pull_request]


jobs:
  compile-iso:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Update the keyring
        run: pacman -Syy --needed --noconfirm archlinux-keyring blackarch-keyring
      - name: Update the system
        run: pacman -Syu --noconfirm
      - name: install necessary utils
        run: pacman -S archiso git bash github-cli neovim --noconfirm
      - name: prepare build environment
        run: mkdir work out && cd iso/ && bash setup.sh && cd ..
      - name: build the image
        run: mkarchiso -v -w work/ -o out/ iso/ 
