name: Test ISO Compilation

on: [push, pull_request]


jobs:
  compile-iso:
    runs-on: ubuntu-latest
    container:
      image: blackarchlinux/blackarch:latest
      options: --privileged
    steps:
      - name: Checkout files
        uses: actions/checkout@v4
      - name: Update the system
        run: pacman -Syu --noconfirm
      - name: install necessary utils
        run: pacman -S archiso git bash github-cli --noconfirm
      - name: prepare build environment
        run: mkdir work out
      - name: build the image
        run: mkarchiso -v -w work/ -o out/ iso/ 
